name: Check Coding Style

on: [push, pull_request]

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
      
    steps:
    - uses: actions/checkout@v2
      
    - name: Run coding style checker
      run: check.sh $(pwd) $(pwd)
      
    - name: Check for errors
      id: errors
      run: |
        echo "::set-output name=has_errors::$(grep -c 'error:' output.txt || true)"
        cat output.txt
      continue-on-error: true
      
    - name: Fail if errors found
      if: steps.errors.outputs.has_errors != '0'
      run: exit 1
      
    - name: Show annotations
      if: steps.errors.outputs.has_errors != '0'
      uses: jacobtomlinson/github-actions-annotations@v1
      with:
        annotations_file: output.txt
