name: Check Coding Style

on: [push, pull_request]

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
      
    steps:
    - uses: actions/checkout@v2
      
    - name: Run coding style checker
      run: check.sh $(pwd) $(pwd)
