name: Chocolatine

on: [push]

jobs:
  checking the coding style:
    runs-on: ubuntu-latest
    steps:
      - name: Checking the coding style
        uses: actions/checkout@v3
        run: |
          docker run --rm -v $(pwd):/appghcr.io/epitech/coding-style-checker:latest
          check.sh $(pwd) $(pwd)


