name: Chocolatine

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  checking_coding_style:
    runs-on: ubuntu-latest
    container: appghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checking files
        uses: actions/checkout@v3

      - name: Checking coding style
        run: |
          check.sh $(pwd) $(pwd)

  check_program_compilation:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checking files
        uses: actions/checkout@v3

      - name: Make
        run: |
          make
      
      - name: Make clean
        run: make clean

  run_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checking files
        uses: actions/checkout@v3

      - name: Make tests_run
        run: |
          make tests_run




