name: Chocolatine

on: [push]

jobs:
  checking_coding_style:
    runs-on: ubuntu-latest
    steps:
      - name: Checking files
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_red }}
      - name: Checking coding style
        run: |
          docker run --rm -v $(pwd):/appghcr.io/epitech/coding-style-checker:latest
          check.sh $(pwd) $(pwd)



